pub type ID = usize;
pub type Version = u8;
pub type Time = u128; // intended to be used as unix time in milliseconds
pub type SequenceNumber = usize;
pub type Variant = u8;
pub type LinkWeight = u16;
pub type ChargeCount = u16;
pub type IterationCount = u8;
pub type PollWeight = u16;
